---
- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL is started
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: localhost

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_user_name }}"
    password: "{{ mysql_user_password }}"
    priv: "*.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: localhost
  become: true

